on: [workflow_dispatch, push, pull_request]

env:
  SFML_DIR: extern/sfml

jobs:
  lint:
    name: Clang-format - ENFORCING DISABLED TEMPORARILY!
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install clang-format
      - name: Run clang-format
        run: clang-format $(find src/impl -type f) --dry-run
#            -Werror
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc: [clang++, g++]
    steps:
      - uses: actions/checkout@v2
      - name: Install SFML dependencies...
        run: sudo apt-get install libgl-dev
      - name: Download & setup SFML/master manually...
        run: ./tooling/sfml-setup
      - name: Build (Ubuntu only! Windows is being manually tested locally for now...)
        run: make CC=${{ matrix.cc }}
